config/routes.rb
Rails.application.routes.draw do

	# resources :homes

	get '*unmatched_route', to: 'application#not_found'
	
	root to: "homes#static_index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
  	render :file => "#{Rails.root}/public/404.html.erb", :status => 404
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]


  # GET /homes
  # GET /homes.json
  def static_index
    render :layout => 'static_layout'
  end


  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/homes/static_index.html.erb
<% content_for :title, "Ninja, coming soon..." %>
<!-- banner -->
<div class="banner-w3">
	<div class="banner-info-w3l">
		<h1>Ninja<span>Under Construction</span></h1>
			<img src="<%= asset_path('icon.png') %>">
			<h2>Coming soon...or not.</h2>
		<div id="countdown"></div>
			<p id="note"></p>
		<div class="copyright">
			<p>© Ninja | Design by <a href="http://w3layouts.com">W3layouts</a></p>
		</div>
	</div>
</div>

app/views/homes/static_index.old.html.erb
<!-- <img src="<%= asset_path('pending.gif') %>" /> -->
<style type="text/css">
	@font-face {
		font-family: 'Blanche';
		src: url(<%= asset_path('BlanchedelaFontaine.ttf') %>) format('truetype');
		font-weight: bold;
		font-style: normal;
	}
	h1 {
		font-family: 'Blanche';
	    color: #fff;
	    text-align: center;
	    font-size: 48px;
	    position: absolute;
	    margin: 25px auto;
	    left: 0;
	    right: 0;
	}
	body {
		background-color: #191f26;
		margin: 0;
		padding: 0;
	}
</style>

<h1>En construction</h1>
<img src="<%= asset_path('pending.gif') %>" style="display: block; margin: 0 auto;" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/static_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="css/jquery.countdown.css" />
	<script src="js/jquery.min.js"></script>
	<script src="js/jquery.countdown.js"></script>
	<script src="js/script.js"></script> -->
    <!--web-fonts-->
	<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'></head>
	<link href='//fonts.googleapis.com/css?family=Candal' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>